---

storage_pool_path: '/home/root/images-vagrant'

pod_subnet: '10.11.0.0/16'
service_subnet: '10.10.1.0/24'
ext_start: '192.168.1.240'
ext_end: '192.168.1.250'
# cluster_name: 'kubernetes'
# k8s_version: 1.18.2
# verbose: -vvv

masters:
  - name: master1
    cc_ip: '10.10.0.10'
    host_port: 6445
    # cpus: 4
    # memory: 16384
    # disk: 50

workers:
  - name: worker1
    cc_ip: '10.10.0.11'
    # cpus: 4
    # memory: 16384
    # disk: 50
