---

- name: Install prerequisites
  yum:
    name: "{{ item }}"
    state: latest
  become: true
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker CE repository
  shell: "yum-config-manager --add-repo {{ docker_repo }}"
  become: true

- name: Install Docker package
  yum:
    name: docker-ce
    state: latest
  become: true

- name: Ensure that docker configuration directory exists
  file:
    path: /etc/docker
    state: directory
  become: true

- name: Configure docke registry
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  become: true

- name: Enable and start Docker
  systemd:
    name: docker
    state: restarted
    enabled: true
  become: true
