---

- name: Gather facts about master
  import_tasks: gather_facts.yml

- name: Ensure kubeadm config directory exists
  file:
    path: "{{ k8s_master_kubeadm_config_file | dirname }}"
    mode: 0775
    state: directory
  become: true

- name: Configure master when not ready
  when:
    not k8s_master_already_exists
    or not k8s_master_role_correct
    or not k8s_master_ready
  block:
    - include_tasks: master_init.yml

- name: Ensure kubectl config directory exists
  file:
    path: "{{ k8s_master_kube_config_file | dirname }}"
    mode: 0775
    state: directory

- name: Copy kubectl config
  copy:
    src: "{{ k8s_master_kube_admin_config_file }}"
    dest: "{{ k8s_master_kube_config_file }}"
    owner: "{{ ansible_user_id | default(ansible_user | default(omit)) }}"
    group: "{{ ansible_user_gid | default(omit) }}"
    remote_src: true
  become: true

- name: Install bash completion
  yum:
    name: bash-completion
    state: latest
  become: true

- name: Configure bash completion for kubernetes
  lineinfile:
    path: "{{ k8s_master_bashrc_file }}"
    line: source <(kubectl completion bash)
